language: java

jdk:
  - oraclejdk7
# Commenting out the openjdk builds because of this travis bug... https://github.com/travis-ci/travis-ci/issues/5227
#  - openjdk7
#  - openjdk6

script:
   - gradle --quiet --no-color --no-search-upward --info test

notifications:
  email: false
  slack:
    secure: mWsEjbJ2vWTqvOIaeosHtMzO1iT3rSYbv+sufQz8bv30syzyz0I0ca8TEQ5TRySDOKbm9wPXupuLadpLqx4HmzHvDeDPZvswZHSKVnWm36Ybb8xzIU10R5BF4Z+vVMwevWNtYAS8/z5jXz4Xm4gQlloFRRvSwjGh14m12qERLkE=
